# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170523_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encurtaurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
