# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170523_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encurtaurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
